**Objetivo:** repetir con un dataset diferente las operaciones vistas con Pingüinos: explorar, seleccionar, filtrar, agrupar, limpiar, transformar y exportar.

**Importante:** usa el material de referencia, documentación y, si lo deseas, un asistente de IA. Debes **entender y comprobar** el código. Las celdas están intencionadamente sin resolver.

## Preparación
Este archivo usa una copia didáctica del dataset Iris con **8 celdas vacías introducidas para practicar limpieza**. Son 150 flores, tres especies y cuatro mediciones. Los datos originales se guardan en `iris_original.csv` para comparar.

Coloca este notebook en la misma carpeta que los archivos CSV. Si aparece `FileNotFoundError`, revisa la carpeta abierta en VS Code.

In [4]:
import pandas as pd

iris = pd.read_csv("iris_con_faltantes.csv")
print("Dataset cargado:", iris.shape)
display(iris.head(3))

Dataset cargado: (150, 5)

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa

**Comprobación esperada:** `(150, 5)`.

**Referencia de columnas:** `sepal_length_cm`, `sepal_width_cm`, `petal_length_cm`, `petal_width_cm`, `species`. Las medidas están expresadas en centímetros.

## Ejercicio 1. Explorar el dataset

a) Muestra las primeras cinco filas. b) Identifica las dimensiones. c) Consulta los tipos de columna y sus valores no nulos. d) Encuentra cuáles especies aparecen en la columna `species`.

**Pista:** Recuerda `head`, `shape`, `info` y `unique`. Debes encontrar **3 especies**.

In [10]:
display(iris.head(150)) #a

print("Dimensiones:", iris.shape) #b

iris.info() #c

print("Especies:", iris["species"].unique()) #d

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,NaN,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

Dimensiones: (150, 5)
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sepal_length_cm  150 non-null    float64
 1   sepal_width_cm   145 non-null    float64
 2   petal_length_cm  150 non-null    float64
 3   petal_width_cm   147 non-null    float64
 4   species          150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB
Especies: <StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

## Ejercicio 2. Seleccionar columnas y posiciones

a) Crea una tabla que contenga solo `species` y `petal_length_cm`. b) Muestra **las cinco primeras filas y las dos primeras columnas** mediante posiciones, no nombres.

**Pista:** Usa una lista de columnas para (a) y `iloc` para (b). El final de un slice no se incluye.

In [11]:
display(iris[["species", "petal_length_cm"]].head(150)) #a

display(iris.iloc[0:5, 0:2]) #b

       species  petal_length_cm
0       setosa              1.4
1       setosa              1.4
2       setosa              1.3
3       setosa              1.5
4       setosa              1.4
..         ...              ...
145  virginica              5.2
146  virginica              5.0
147  virginica              5.2
148  virginica              5.4
149  virginica              5.1

[150 rows x 2 columns]

   sepal_length_cm  sepal_width_cm
0              5.1             3.5
1              4.9             3.0
2              4.7             3.2
3              4.6             3.1
4              5.0             NaN

## Ejercicio 3. Filtrar con una o dos condiciones

a) Selecciona solamente flores de la especie `setosa`. b) Selecciona flores de `virginica` cuyo `petal_length_cm` sea **mayor que 5.5**. c) Muestra cuántas filas tiene cada resultado.

**Pista:** Utiliza una máscara de comparación y `&`; cada condición debe ir entre paréntesis.

In [14]:
mascara1 = iris["species"] == "setosa"
seleccion1 = iris.loc[mascara1, ["species", "petal_length_cm"]]
print("Coincidencias setosa:", len(seleccion1)) #a

mascara2 = (iris["species"] == "virginica") & (iris["petal_length_cm"] > 5.5)
seleccion2 = iris.loc[mascara2, ["species", "petal_length_cm"]]
print("Coincidencias virginica con largo de pétalo > 5.5 cm:", len(seleccion2)) #b

Coincidencias setosa: 50
Coincidencias virginica con largo de pétalo > 5.5 cm: 25

## Ejercicio 4. Contar y agrupar por especie

a) Cuenta cuántas flores hay de cada especie. b) Calcula el **promedio de `petal_length_cm` para cada especie**. c) Identifica cuál tiene el promedio mayor.

**Pista:** Busca `value_counts`, `groupby` y `mean`. La columna `petal_length_cm` no contiene faltantes en esta copia.

In [25]:
species_counts = iris["species"].value_counts()
print("Cantidad de flores por especie:\n", species_counts) #a

groupby_species = iris.groupby("species")
mean_petal_length = groupby_species["petal_length_cm"].mean()
print("\nPromedio de largo de pétalo por especie:\n", mean_petal_length) #b

for species, mean_length in mean_petal_length.items():
    if mean_length == mean_petal_length.max():
        print(f"\nEspecie con mayor promedio de largo de pétalo: {species} ({mean_length} cm)") #c

Cantidad de flores por especie:
 species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

Promedio de largo de pétalo por especie:
 species
setosa        1.462
versicolor    4.260
virginica     5.552
Name: petal_length_cm, dtype: float64

Especie con mayor promedio de largo de pétalo: virginica (5.5520000000000005 cm)

## Ejercicio 5. Limpiar valores faltantes y quitar columnas

a) Cuenta cuántos valores faltan por columna. b) Crea **una copia** sin las filas que tengan valores vacíos y cuenta cuántas quedan. c) Crea otra copia donde rellenes únicamente los faltantes de `sepal_width_cm` con su mediana. d) Crea una tercera copia sin la columna `petal_width_cm`. **No modifiques `iris` directamente.**

**Pista:** Recuerda `isna().sum()`, `dropna()`, `fillna()`, `median()` y `drop(columns=[...])`. Esperamos **142 filas completas** antes de rellenar.

In [ ]:
iris.isna().sum()
print("Cantidad de valores faltantes por columna:\n", iris.isna().sum()) #a

iris_dropna = iris.copy().dropna()
print("Dimensiones después de eliminar filas con valores faltantes:", iris_dropna.shape) #b

Cantidad de valores faltantes por columna:
 sepal_length_cm    0
sepal_width_cm     5
petal_length_cm    0
petal_width_cm     3
species            0
dtype: int64
Dimensiones después de eliminar filas con valores faltantes: (142, 5)

TypeError: Cannot perform reduction 'median' with string dtype

## Ejercicio 6. Transformar columnas

a) Crea en una copia una nueva columna `petal_length_mm` convirtiendo centímetros a milímetros. b) Crea otra columna `species_codigo` asignando `S`, `V` y `G` a las tres especies. c) Comprueba cinco filas.

**Pista:** Para la conversión basta una operación sobre toda la columna; para códigos puedes usar `.map()` con un diccionario. Si quieres, prueba también `.apply(lambda ...)`.

In [ ]:
# Escribe tu solución aquí

## Ejercicio 7. Exportar el resultado

a) Guarda el DataFrame transformado del ejercicio 6 en `iris_procesado.csv`, **sin guardar la columna de índice**. b) Vuelve a leer el CSV con Pandas y comprueba que conserva 150 filas y las nuevas columnas.

**Pista:** Usa `to_csv` con `index=False` y después `read_csv`.

In [ ]:
# Escribe tu solución aquí

## Ejercicio 8. Unir filas con `concat`

a) Construye dos DataFrames: primeras 50 filas y siguientes 50 filas de `iris`. b) Únelos verticalmente y comprueba el número total de filas.

**Pista:** Combina `iloc` y `pd.concat`; prueba `ignore_index=True`.

In [ ]:
# Escribe tu solución aquí

## Ejercicio 9. Relacionar tablas con `merge`
Crea una tabla pequeña con las columnas `species` y `codigo`: setosa→S, versicolor→V y virginica→G. Une esta tabla con `iris` mediante la especie. Verifica que aparecen 150 filas y una columna adicional. Los códigos son solamente etiquetas didácticas.

**Pista:** Puedes construir la tabla auxiliar con `pd.DataFrame({...})` y hacer un `merge` por `species`.

In [ ]:
# Escribe tu solución aquí

## Antes de entregar
**Guarde en un Github creado Público** `git status` → `git add .` → `git commit -m "Practicar consultas y transformaciones con Pandas"`. Evita subir al repositorio archivos de entornos virtuales (`.venv/`).